const fileList = {
    "0": "fall a land to run forward.fbx",
    // "1": "fall a land to standing idle 01.fbx",
    // "2": "fall a loop.fbx",
    // "3": "standing aim overdraw.fbx",
    "4": "standing aim recoil.2.fbx",
    // "5": "standing aim walk back.fbx",
    // "6": "standing aim walk forward.fbx",
    // "7": "standing aim walk left.fbx",
    // "8": "standing aim walk right.fbx",
    // "9": "standing block.fbx",
    // "10": "standing death backward 01.fbx",
    // "11": "standing death forward 01.fbx",
    // "12": "standing disarm bow.fbx",
    // "13": "standing dive forward.fbx",
    // "14": "standing dodge backward.fbx",
    // "15": "standing dodge forward.fbx",
    // "16": "standing dodge left.fbx",
    // "17": "standing dodge right.fbx",
    // "18": "standing draw arrow.fbx",
    // "19": "standing equip bow.fbx",
    "20": "standing idle 01.fbx",
    // "21": "standing idle 02 looking.fbx",
    // "22": "standing idle 03 examine.fbx",
    // "23": "standing melee kick.fbx",
    // "24": "standing melee punch.fbx",
    // "25": "standing react small from front.fbx",
    // "26": "standing react small from headshot.fbx",
    // "27": "standing run back.fbx",
    // "28": "standing run forward stop.fbx",
    // "29": "standing run forward.fbx",
    // "30": "standing run left.fbx",
    // "31": "standing run right.fbx",
    // "32": "standing turn 90 left.fbx",
    // "33": "standing turn 90 right.fbx",
    "34": "standing walk back.fbx",
    "35": "standing walk forward.fbx",
    "36": "standing walk left.fbx",
    "37": "standing walk right.fbx",
    // "38": "unarmed idle 01.fbx",
    "erika": "erika_archer_bow_arrow.fbx"
}

export default fileList