let fileList = {
    "0": "crouch idle.fbx",
    // "1": "crouch to standing idle.fbx",
    // "2": "standing block idle.fbx",
    // "3": "standing block react large.fbx",
    // "4": "standing disarm over shoulder.fbx",
    // "5": "standing disarm underarm.fbx",
    // "6": "standing idle looking ver. 1.fbx",
    // "7": "standing idle looking ver. 2.fbx",
    "8": "standing idle.fbx",
    "9": "standing jump.fbx",
    // "10": "standing melee attack 360 high.fbx",
    // "11": "standing melee attack 360 low.fbx",
    // "12": "standing melee attack backhand.fbx",
    // "13": "standing melee attack downward.fbx",
    // "14": "standing melee attack horizontal.fbx",
    // "15": "standing melee attack kick ver. 1.fbx",
    // "16": "standing melee attack kick ver. 2.fbx",
    // "17": "standing melee combo attack ver. 1.fbx",
    // "18": "standing melee combo attack ver. 2.fbx",
    // "19": "standing melee combo attack ver. 3.fbx",
    // "20": "standing melee run jump attack.fbx",
    // "21": "standing react large from left.fbx",
    // "22": "standing react large from right.fbx",
    // "23": "standing react large gut.fbx",
    "24": "standing run back.fbx",
    "25": "standing run forward.fbx",
    // "26": "standing taunt battlecry.fbx",
    // "27": "standing taunt chest thump.fbx",
    // "28": "standing turn left 90.fbx",
    // "29": "standing turn right 90.fbx",
    // "30": "standing walk back.fbx",
    // "31": "standing walk forward.fbx",
    // "32": "standing walk left.fbx",
    // "33": "standing walk right.fbx",
    // "34": "unarmed equip over shoulder.fbx",
    // "35": "unarmed equip underarm.fbx",
    // "36": "unarmed idle looking ver. 1.fbx",
    // "37": "unarmed idle looking ver. 2.fbx",
    // "38": "unarmed idle.fbx",
    // "39": "unarmed jump running.fbx",
    // "40": "unarmed jump.fbx",
    // "41": "unarmed run back.fbx",
    // "42": "unarmed run forward.fbx",
    // "43": "unarmed turn left 90.fbx",
    // "44": "unarmed turn right 90.fbx",
    // "45": "unarmed walk back.fbx",
    // "46": "unarmed walk forward.fbx",
    "45": "Standing Death Forward 01.fbx",
    'maw': 'Maw.fbx'
}
export default fileList